#!/bin/bash
# instala la llave gpg
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
# asegura que apt trabaja con fuentes https
sudo apt install apt-transport-https -y
# se descarga el paquete de la version estable
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
# se actualizan las fuentes apt
sudo apt update -y
# se instala sublime text 3
sudo apt install sublime-text -y
