#!/bin/bash

# Tabla creada con el comando printf

printf "\e[1;31m%-5s %-10s %-4s\n\e[0m" No Name Mark
printf "%-5s %-10s %-4.2f\n" 1 Sarath 80.3456
printf "%-5s %-10s %-4.2f\n" 2 James 90.9989
printf "%-5s %-10s %-4.2f\n" 3 Jeff 77.564
