#!/bin/bash
# Validando el usuario root en un script para notificar en el momento de ejecución para solicitar privilegios elevados.

if [ $UID -ne 0 ]; then
	echo -e "Necesitas ser superusuario para ejecutar este script"
else
	echo -e "Procediendo a la ejecución de este script como superusuario"
fi
