#!/bin/bash
# nombre: install_own_commands
# descripcion: instala comandos propios 
# fecha: 27/04/2018
# autor: ArtadminMX

# Habrá varias carpetas, una de ejecutables llamada bin, otra de scripts llamada script

# comprobamos que se ejecute todo el script con permisos de superusuario
if [ $UID -ne 0 ]; then
	echo -e "Es mejor que ejecutes este script como usuario root para evitar conflictos"
else 
	echo -e "Se procede a la instalación de tus comandos"
	bindir=$HOME/.local/bin
	# comprobamos que exista el directorio ~/.local/bin
	if [ -d "$bindir" ]; then
		echo -e "Ya existe el directorio bin en ~/.local"
	else
		# se crea el directorio si no existe
		echo -e "Aún no existe el directorio bin,"
		echo -e "Creando el directorio..."
		mkdir $bindir
		chown $USER:$USER $bindir
		chmod 755 $bindir
	fi
	# copiando binarios, commandos y creando links
	cp bin/HDSentinel /sbin/
	chown root:root /sbin/HDSentinel
	chmod 755 /sbin/HDSentinel
	cp script/hds $bindir
	chown root:root $bindir/hds
	chmod 755 $bindir/hds
	ln -s $bindir/hds /bin/hds
	ln -s $bindir/hds /sbin/hds

	# Instalacion de sublime text
	# instala la llave gpg
	wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
	# asegura que apt trabaja con fuentes https
	sudo apt install apt-transport-https -y
	# se descarga el paquete de la version estable
	echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
	# se actualizan las fuentes apt
	sudo apt update -y
	# se instala sublime text 3
	sudo apt install sublime-text -y
	# copiando comando y creando links
	cp script/st $bindir
	chown root:root $bindir/st
	chmod 755 $bindir/st
	ln -s $bindir/st /bin/st
	ln -s $bindir/st /sbin/st

	# Instalar otros programas de administracion
	sudo apt install gparted -y
	sudo apt install baobab -y
fi